INSERT INTO grupo_permissao (`grupo_id`, `permissao_id`) VALUES 
(1, 1)  , -- MASTER: ALLOWS_CONSULT_EMPRESA 
(1, 2)  , -- MASTER: ALLOWS_REGISTER_EMPRESA
(1, 3)  , -- MASTER: ALLOWS_UPDATE_EMPRESA  
(1, 4)  , -- MASTER: ALLOWS_DELETE_EMPRESA 
(1, 5)  , -- MASTER: ALLOWS_CONSULT_FUNCIONARIO
(1, 6)  , -- MASTER: ALLOWS_REGISTER_FUNCIONARIO
(1, 7)  , -- MASTER: ALLOWS_UPDATE_FUNCIONARIO  
(1, 8)  , -- MASTER: ALLOWS_DELETE_FUNCIONARIO  
(1, 9)  , -- MASTER: ALLOWS_CONSULT_PONTO
(1, 10) , -- MASTER: ALLOWS_REGISTER_PONTO
(1, 11) , -- MASTER: ALLOWS_UPDATE_PONTO  
(1, 12) , -- MASTER: ALLOWS_DELETE_PONTO 

(2, 1)  , -- ADMIN: ALLOWS_CONSULT_EMPRESA
(2, 3)  , -- ADMIN: ALLOWS_UPDATE_EMPRESA
(2, 5)  , -- ADMIN: ALLOWS_CONSULT_FUNCIONARIO
(2, 6)  , -- ADMIN: ALLOWS_REGISTER_FUNCIONARIO
(2, 7)  , -- ADMIN: ALLOWS_UPDATE_FUNCIONARIO
(2, 8)  , -- ADMIN: ALLOWS_DELETE_FUNCIONARIO
(2, 9)  , -- ADMIN: ALLOWS_CONSULT_PONTO
(2, 10) , -- ADMIN: ALLOWS_REGISTER_PONTO
(2, 11) , -- ADMIN: ALLOWS_UPDATE_PONTO
(2, 12) , -- ADMIN: ALLOWS_DELETE_PONTO

(3, 9)  , -- USER: ALLOWS_CONSULT_PONTO
(3, 10) , -- USER: ALLOWS_REGISTER_PONTO
(3, 11) ; -- USER: ALLOWS_UPDATE_PONTO